"""Add image_url and image_description to Product

Revision ID: 5cdd9c934f54
Revises: a1e79b426e0d
Create Date: 2025-12-12 16:38:15.508092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdd9c934f54'
down_revision: Union[str, None] = 'a1e79b426e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True, comment='URL to product image (local or remote)'))
    op.add_column('products', sa.Column('image_description', sa.Text(), nullable=True, comment='AI-generated description of product appearance for image generation'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_description')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
