"""add_video_project_and_scene_image

Revision ID: a1e79b426e0d
Revises: 004_remove_brand_id
Create Date: 2025-12-12 08:31:21.700629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a1e79b426e0d'
down_revision: Union[str, None] = '004_remove_brand_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'product_category',
               existing_type=mysql.VARCHAR(length=50),
               comment='serum, cream, toner, essence, oil, mask, cleanser, sunscreen, moisturizer, etc.',
               existing_nullable=True)
    op.alter_column('products', 'skin_concerns',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               comment='acne, pores, wrinkles, dark_spots, dullness, redness, dryness, etc.',
               existing_comment='acne, pores, wrinkles, dark_spots, dullness, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'skin_concerns',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               comment='acne, pores, wrinkles, dark_spots, dullness, etc.',
               existing_comment='acne, pores, wrinkles, dark_spots, dullness, redness, dryness, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('products', 'product_category',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='serum, cream, toner, essence, oil, mask, cleanser, sunscreen, moisturizer, etc.',
               existing_nullable=True)
    # ### end Alembic commands ###
