"""add_reference_image_urls_to_image_projects

Revision ID: d369739c4785
Revises: 5f34e9a45e2f
Create Date: 2025-12-26 22:44:48.602108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd369739c4785'
down_revision: Union[str, None] = '5f34e9a45e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_projects', sa.Column('reference_image_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_projects', 'reference_image_urls')
    # ### end Alembic commands ###
